### ISSUE TITLE
[solved] Resource Manager does not show files, the path to the correct folder.

### ISSUE THREAD

**Issue by Drui7** [HearthSim/HDT-Localization#101]
problem solved by updating the program for translation

**Comment by Zawodowiec1532** [comment]
Hmm, are you sure ResX have premissions to read from this folder? Maybe try run it as Admin.
Also check your config (Configuration button on bottom of application).
Here is default: https://i.imgur.com/Y8ialdN.png

**Comment by Drui7** [comment]
@Zawodowiec1532 running with administrator rights.
![default](https://user-images.githubusercontent.com/3121957/37385559-2d37b84c-2776-11e8-8cd0-17f48148219f.png)
