### ISSUE TITLE
Some strings have and lower dash in it, is it normal? Should it be included in the translation?

### ISSUE THREAD

**Issue by Maxiride** [HearthSim/HDT-Localization#121]
I wante to help translate in italian the HDT however I'm in doubt regarding some strings that have a "_" in it. Should it be included both when it appears at the beginning of the string and also when it is in the middle of it like "P_aladin" or "Wa_rrior"?

![image](https://user-images.githubusercontent.com/3630857/38777596-e89faad4-40aa-11e8-8288-3e84c971b077.png)

**Comment by azeier** [comment]
This is used for Alt+{key} menu controls. Pressing e.g. Alt+{N} in HDT will open the "New" menu item.

Whether you want to implement this in Italian is up to you, I don't think it's gets much use anyway.

**Comment by Maxiride** [comment]
Thanks for the clarification =) Didn't knew they were for the shortcuts.

**Comment by Maxiride** [comment]
I'm confused, I started translating a lot of lines using the previously suggested tool ResX but now I see in that the project moved to Crowdin. Should I trash the work done so far? How can I re-start translating in Crowdin?

**Comment by azeier** [comment]
Alright, uploaded it. You can sign up and request access here: https://translate.hsdecktracker.net/project/hearthstone-deck-tracker/it#

**Comment by Maxiride** [comment]
Will do!
