### ISSUE TITLE
Please give the program another symbol for the line length

### ISSUE THREAD

**Issue by Drui7** [HearthSim/HDT-Localization#18]
The word "use" in English is very short (in Russian 12 characters), I was able to choose a short (in Russian) analogue "select" (in Russian 7 characters), but the first letter is not displayed completely, or not displayed.
![default](https://cloud.githubusercontent.com/assets/3121957/20865821/248745f6-ba3e-11e6-9693-c52392cafb50.JPG)
It is shown: ВЫБРАНО or ВЫБРАТЬ
but without showing the first letter В

**Comment by azeier** [comment]
Will be fixed with the next HDT release.
