### ISSUE TITLE
Could you add me into the  Chinese-simplified translation group?

### ISSUE THREAD

**Issue by chucklu** [HearthSim/HDT-Localization#180]
I have sent you a message through crowdin on 3rd March.
![image](https://user-images.githubusercontent.com/3004057/77819146-8bae6180-7113-11ea-9d21-c35ae1ae81fb.png)

**Comment by chucklu** [comment]
I have sent the request to join the translation teams one month ago.
![image](https://user-images.githubusercontent.com/3004057/78017282-9de00800-737e-11ea-8c11-d796eaf55b79.png)
![image](https://user-images.githubusercontent.com/3004057/78017301-a2a4bc00-737e-11ea-8acc-83c1a26bf247.png)

**Comment by chucklu** [comment]
@azeier which one I supposed to contact to approve my request? Who is responsible for approve the request? **Why nobody handle the request?**
![image](https://user-images.githubusercontent.com/3004057/78018696-f0222880-7380-11ea-9b54-b08ae9ab9551.png)

**Comment by azeier** [comment]
(I seem to have missed this issue)

We have someone maintaining contributors to the other crowdin projects, but apparently not HDT. Sorry about that, I accepted your request now. And thank you for helping with the translations!
