### ISSUE TITLE
Localization of hsdata

### ISSUE THREAD

**Issue by olloff** [HearthSim/HDT-Localization#31]
Hi. Again.
Say, if someone tries to translate https://github.com/HearthSim/hsdata, would be there any problem to use new culture param in HDT in tooltips and flavor?

**Comment by jleclanche** [comment]
I don't understand what you're asking.

**Comment by olloff** [comment]
Sorry, was not sure if it clear enough.

CardDefs.xml contains different language tags/cultures used by HDT to provide card description, flavor text, etc. 
Could I just add a new tag (as in example below) and therefore provide new card data source for HDT? 

```
<CardDefs build="17470">
	<Entity CardID="AT_001" ID="2539" version="2">
		<MasterPower>7741f56d-95c5-424c-9586-266a51d27290</MasterPower>
		<Tag enumID="185" name="CARDNAME" type="LocString">
			<enUS>Flame Lance</enUS>
			...
			<ukUA>Вогняний спис</ukUA> //new lang tag
			...
			<deDE>Flammenlanze</deDE>
			<ruRU>Огненное копье</ruRU>
			...
		</Tag>
		...
	</Entity>
</CardDefs>
```

**Comment by jleclanche** [comment]
No, hsdata is autogenerated from the game files.

If you want to add another language to that you can talk to Blizzard :)

**Comment by Drui7** [comment]
If you can convince Blizzard to it, then do persuade the death knight for Hearthstone and release the game for Linux. :D

**Comment by olloff** [comment]
@jleclanche I trust your opinion, but can't tell if you understand me right.
I'm not proposing to add a new language to the game itself, its literally impossible for Blizzard to do something other, than notorious Blizzard Way. But add that to HDT so the new primary/secondary tooltip language could be set.

I just tried to split autogenerated xml by language tags. And, i believe, it could be merged back with the same ease. Its like no big deal to have hsdata populated with the new tag.
The real questions is: does HDT uses hsdata as its source of card information (sorry, its not very clear for me)? And could HDT use new language tag without serious modifications?

**Comment by jleclanche** [comment]
I understand what you're saying, but hsdata is autogenerated from the game files and it's far too much complexity to include other languages in there for it to be worth it.

**Comment by Fidetro** [comment]
I am looking for a way to translate the race field in the api,I also checked this repository, https://github.com/HearthSim/HDT-Localization, and it doesn't look like there's a way to get the translated language directly from what's in the race field?
https://api.hearthstonejson.com/v1/121569/zhCN/cards.json
