### ISSUE TITLE
Current file EN for translation in French

### ISSUE THREAD

**Issue by Havok56** [HearthSim/HDT-Localization#54]
Hello,
I want translate HDT in French. I begun with the DE.resx but it not complet.
I would to know, where can I find the most recent file in EN ?
Thanks.

**Comment by azeier** [comment]
Hey,

someone is currently working on the french translation, I linked him to this issue.
Just so you guys don't do duplicate work.


As for the actual question: The original is in Strings.resx. I recommend you use the cool linked here: https://github.com/HearthSim/HDT-Localization#recommended-software

**Comment by Havok56** [comment]
I have not seen any topic about this and the file in HDT-Localization has not been updated for 9 months...
Thank you for your answer.

**Comment by azeier** [comment]
He just reached out to me on discord a few days ago. I imagine he is still a bit away from being done, so you guys can probably split the work :).

**Comment by Havok56** [comment]
Ok thanks. I wait for her news.

**Comment by fdela** [comment]
Well, I'm actually almost done translating it. It should be done in a couple of days. You'll be able to review it afterwards if you feel like it.

**Comment by Havok56** [comment]
Ok merci ! ;)

**Comment by azeier** [comment]
French translation PR has been merged.
