### ISSUE TITLE
missing card with filter translation

### ISSUE THREAD

**Issue by sdbds** [HearthSim/HDT-Localization#6]
![image](https://cloud.githubusercontent.com/assets/8085926/18740820/4d3bbb9c-80de-11e6-8cb9-60d9e4b1507d.png)

![image](https://cloud.githubusercontent.com/assets/8085926/18740832/5b7165f4-80de-11e6-9cc8-a9d60b328ab2.png)

**Comment by dyx00001** [comment]
我也是遇到這個問題@sdbds

**Comment by azeier** [comment]
I'm not entirely sure what this refers to, but I think this is fixed since that part of the UI no longer exists.
